### ISSUE TITLE
 "'locale' is undefined", bug in knopki.locale 1.0.3, fixed in master.

### ISSUE THREAD

**Issue by leonelgalan** [mikolak-net/ansible-raspi-config#1]
Output
```
TASK [knopki.locale : set locale to {{ locale }}] ******************************
task path: /usr/local/etc/ansible/roles/knopki.locale/tasks/main.yml:7
fatal: [192.168.1.24]: FAILED! => {"failed": true, "msg": "'locale' is undefined"}
```

Pointing dependency to master, still no tag or simply adding a `locale` var to mikolak.raspi-config, this is simply used in a label in https://github.com/knopki/ansible-locale/blob/v1.0.3/tasks/main.yml#L7, it's not used anywhere else.

**Comment by mikolak-net** [comment]
@leonelgalan thanks for the report, I'll try to repro it (looks like a simple fix anyway). What's your:
 - RasPi model?
 - OS distro/version?
 - Ansible version?

**Comment by leonelgalan** [comment]
- RasPi 3
- RASPBIAN JESSIE
- ansible 2.0.1.0

But, the issue should happen independent of these. It looks like leftover from a previous feature/way of doing things.

**Comment by mikolak-net** [comment]
@leonelgalan it actually looks like an incompatibility issue with 2.x. As you can see from the ref above, the fix is in repo, including others related to the semantic changes in the new Ansible version(s).

It's packaged in release `1.1.2`, already Available on Galaxy.

Thanks again for the report, and I'm glad this little project has been helpful to you :).
