### ISSUE TITLE
Timeout fails

### ISSUE THREAD

**Issue by mikolak-net** [mikolak-net/ansible-raspi-config#9]
It seem we have another regression, at least on RPi 2B+. On a fresh install, the timeout seems to hang and fail, despite the machine restarting.

**Comment by colin-nolan** [comment]
I also started having problems with the timeout, around the time you posted this (I haven't got around to looking into it until now though).

For me, the issue is that the reboot task fails *every time*, claiming the server becomes unreachable. I'm not sure if it's related to the problem you've encountered but it's suspicious...

I've looked into the issue and I think I understand what's going wrong. The `async` property (which is [very poorly documented](http://docs.ansible.com/ansible/playbooks_async.html)) defines the maximum runtime of the async task (in seconds). On the `reboot` handler, this is set to `0` - the meaning of this value is undefined as far as I can determine without looking at the source.

In my tests, a task executes synchronously when `async` it is set to `0`. e.g.
```
- local_action: shell date +'%T'
# 00:29:26

- shell: "sleep 60"
   async: 0
   poll: 0

- local_action: shell date +'%T'
# 00:30:28
```

If I change the `async` value on the reboot task to a larger value and it works as expected:
```
    - name: reboot
      become: yes
      shell: "reboot"
      async: 1000
      poll: 0
```

The previous workaround with the extra sleep (which is discussed here: https://github.com/ansible/ansible/issues/14413) does not appear to be required if `async > 0` and it actually runs as a fire-and-forget task.

I'll make a fix and prehaps you can see if this also solves the problem you were having?
